.github/workflows/release.yml
Dockerfile

This is copied in whole from source-controller, and adapted by replacing `source-controller` with `image-reflector-controller` (only).

Add release workflow

---

.github/workflows/release.yml
Dockerfile

.. from image-automation-controller. It is exactly the same except for the name of the controller, used in various capacities.

Port the parameterised release workflow here

---

main.go

This adds an option to allow configuration of all namespaces, or a specific namespace (configured by `RUNTIME_NAMESPACE`) for the manager cache.
Fix: #51

Allow configurability of all namespaces vs a specific namespace.

---

controllers/suite_test.go

Badger will panic with a nil pointer dereference if you do a transaction after a database is closed. In the controller test suite, the database is closed but the controllers, which read from it, are left running.
To remove this race, it is necessary to tell the controller manager explicitly to shut down; this is done by cancelling the context given to it. This isn't synchronous, because the manager is running in its own goroutine, and cancelling a context can't block until all the consequences are done -- but it may be good enough for our purposes. (If not, we can add some shutdown protocol to the controllers, e.g., channels which they close when exiting).

Avoid race between DB reads and DB close in tests

---

controllers/imagerepository_controller.go
go.mod
go.sum

To include a bug fix to the `ReconcilateAtChangedPredicate`
and renaming to `ReconcileRequestedPredicate`.

Upgrade runtime package to v0.6.2

---

.github/workflows/build.yaml
go.mod
go.sum

Changes:
- use `github.com/dgraph-io/badger/v3 v3.0.0-20210118150219-63f09c34dec1` that includes fixes for ARM 32bit
- enable multi-arch build for PRs

Fix ARM build

---

main.go

This is meant to prevent memory allocation issues on 32bit ARMv7
systems.
The current default value is 1<<28 (268435456 bytes = 256 MiB), which would yield a size
of 512MiB for the value log memory-mapped file.
Note: I've managed to test this successfully on my RPi v3 (only the init phase, as I have no k8s setup to use).
Fixes #82

Allow adjusting Badger's value log file size

---

api/v1alpha1/imagerepository_types.go
config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml

Fix "last scan" print column for ImageRepository

---

CHANGELOG.md
Makefile
config/manager/kustomization.yaml
docs/api/image-reflector.md
go.mod

Release v0.7.1

---

controllers/imagerepository_controller.go
controllers/secret_test.go
controllers/testdata/auth_secret_with_http.json
controllers/testdata/auth_secret_with_http_and_port.json
controllers/testdata/auth_secret_with_port_without_https.json
controllers/testdata/auth_secret_without_https.json
controllers/testdata/secret2.json

Fix: #124 
Fix: #131
Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>

Parse docker auths and use only hostname

---

api/go.mod
api/go.sum
controllers/imagepolicy_controller.go
controllers/imagerepository_controller.go
go.mod
go.sum

Changes:
- Update fluxcd/pkg/runtime to v0.11.0 (ref: fluxcd/pkg#96)
- Use `patch` instead of `update` to set status

Runtime update and status patching

---

config/samples/image_v1beta1_imagepolicy.yaml
config/samples/image_v1beta1_imagerepository.yaml

(the specs need no changes, as this promotion didn't change anything)
Fixes #157.

Correct apiVersion of v1beta1 samples

---

.github/workflows/build.yaml
config/crd/bases/image.toolkit.fluxcd.io_imagepolicies.yaml
config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml

Followup #189 the defaults were added to the wrong APIs.

Check if working tree is dirty in CI

---

.github/workflows/build.yaml
.github/workflows/cifuzz.yaml
.github/workflows/nightly.yaml
.github/workflows/release.yml
.github/workflows/scan.yml
.goreleaser.yaml
config/manager/deployment.yaml

This PR implements:
- https://github.com/fluxcd/flux2/issues/2302
- https://github.com/fluxcd/flux2/issues/2303

Publish SBOM and sign release artifacts

---

README.md
docs/spec/v1alpha1/imagerepositories.md
docs/spec/v1alpha2/imagerepositories.md
docs/spec/v1beta1/imagerepositories.md

Signed-off-by: Daniel Holbach <daniel@weave.works>

update toolkit.fluxcd.io docs links

---

docs/spec/v1beta1/imagerepositories.md

Add service account name to API docs

---

controllers/scan_test.go

Fix flaky tests after adding finalizers

Use unique resources in tests

---

.github/workflows/build.yaml
Dockerfile
Makefile
api/go.mod
go.mod

Relates to https://github.com/fluxcd/flux2/issues/2696/.

build: Upgrade to Go 1.18

---

controllers/imagepolicy_controller.go
controllers/imagerepository_controller.go

Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>
Implements RecoverPanic option on reconciler.
part of [issue #2952](https://github.com/fluxcd/flux2/issues/2952#issue-1325576799)

Enable RecoverPanic option on reconciler

---

CHANGELOG.md
DEVELOPMENT.md
README.md
docs/spec/v1alpha1/imagerepositories.md
docs/spec/v1alpha2/imagerepositories.md
docs/spec/v1beta1/imagerepositories.md

Signed-off-by: Daniel Holbach <daniel@weave.works>

update to new doc links structure

---

Dockerfile

Dockerfile: Build with Go 1.19

---

CHANGELOG.md
config/manager/kustomization.yaml
go.mod

Ref: https://github.com/fluxcd/flux2/issues/3228

Release v0.22.1

---

.github/workflows/release.yml

Ref: https://github.com/fluxcd/flux2/issues/3522

build: Enable SBOM and SLSA Provenance

---

.github/workflows/nightly.yaml
.github/workflows/release.yml
.github/workflows/scan.yml

Part of https://github.com/fluxcd/flux2/issues/3663

build: update release workflow 

---

CHANGELOG.md
config/manager/kustomization.yaml
go.mod

Part of: https://github.com/fluxcd/flux2/issues/3842

Release v0.27.1

---

.github/dependabot.yaml
.github/workflows/build.yaml
.github/workflows/cifuzz.yaml
.github/workflows/nightly.yaml
.github/workflows/release.yml
.github/workflows/scan.yml

Part of: https://github.com/fluxcd/flux2/issues/3709

Update workflows and enable dependabot

---

CHANGELOG.md
config/manager/kustomization.yaml
go.mod

Part of: https://github.com/fluxcd/flux2/issues/3911

Release v0.28.0

---

CHANGELOG.md
config/manager/kustomization.yaml
go.mod

Part of: https://github.com/fluxcd/flux2/issues/4410

Release v0.31.1

---

Makefile
config/crd/bases/image.toolkit.fluxcd.io_imagepolicies.yaml
config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml

Part of: https://github.com/fluxcd/flux2/issues/4947

Update controller-gen to v0.16.1

---

.github/workflows/integration-aws.yaml
.github/workflows/integration-azure.yaml
.github/workflows/integration-gcp.yaml

Refer https://github.com/fluxcd/pkg/pull/839 for details.
CI results:
- GCP https://github.com/fluxcd/image-reflector-controller/actions/runs/12259245700/job/34202043816
- AWS https://github.com/fluxcd/image-reflector-controller/actions/runs/12259467574/job/34201686441

workflows: Use setup-terraform to install latest

---

docs/spec/v1beta2/imagerepositories.md

Part of: https://github.com/fluxcd/flux2/issues/5022

[RFC-0010] Link workload identity docs to complete guide

---

CHANGELOG.md
config/manager/kustomization.yaml
go.mod

Part of: https://github.com/fluxcd/flux2/issues/5363

Release v0.35.0

---

internal/controller/imagepolicy_controller.go
internal/controller/imagepolicy_controller_test.go

Fix ImagePolicy reconciler getting triggered when ImageRepository is not ready

---

docs/spec/v1beta2/imagerepositories.md

xref: https://github.com/fluxcd/flux2/issues/5433#issuecomment-3116877847
```
├── Field descriptions (tls.crt, tls.key, ca.crt) scattered in text
├── Generic explanation of field combinations
├── PEM encoding note and flux create command
└── Single mixed example (mTLS fields + note about CA-only usage)
```
```
├── #### Supported configurations
│   ├── Mutual TLS (mTLS): Client certificate authentication
│   └── CA-only: Server authentication
├── #### Mutual TLS Authentication
│   ├── Detailed explanation and requirements
│   └── ##### Example: mTLS Configuration
│       └── [Complete mTLS example with tls.crt + tls.key + ca.crt]
└── #### CA Certificate Authentication
├── Clear explanation of CA-only use case
└── ##### Example: CA Certificate Configuration
└── [Focused CA-only example]
```

docs: improve mTLS documentation structure and visibility

---

go.mod
go.sum
internal/registry/options.go

ref: https://github.com/fluxcd/pkg/pull/1007, https://github.com/fluxcd/pkg/pull/993

Remove TLS ServerName pinning in TLS config creation

---

go.mod
go.sum
internal/controller/imagepolicy_controller_test.go
internal/registry/options.go
main.go

[RFC-0010] Add default-service-account for lockdown

---

CHANGELOG.md

(cherry picked from commit 89adcecf4e33add44d2799dbdb084b9fbce87cb3)

Add changelog entry for v1.0.2
