- PROJECT
- README.md
- controllers/imagepolicy_controller.go
- controllers/imagerepository_controller.go
- controllers/policy_test.go
- controllers/scan_test.go
- controllers/suite_test.go
- go.mod
- main.go
To keep the pieces of the design separate, it's convenient for the automation controller to have its own repository. That means this repository will deal only with the reflection of image metadata into the cluster; and, the longer name seems more the gitops toolkit way.
> Rename image-update -> image-reflector-controller

- config/default/kustomization.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_webhook_patch.yaml
- config/default/namespace.yaml
- add a namespace resource at the top (used to be in manager/)
- replace original namespace `image-update-system` with
`image-reflector-system`
- don't rely on a name prefix; it's unnecessary and confusing
> Standardise namespace used in config

- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_webhook_patch.yaml
In the most recent kustomize version, the patches in config/default/
fail to apply. (`kubectl apply -k` does not use the most kustomize
version, and seems to cope fine.)
> Make patches work with kustomize build

- .github/workflows/build.yaml
(on that last: grep turns up no hard-coded branch name; not too surprising as this controller doesn't deal with git)
> Follow up to changing the default branch to 'main'

- api/v1alpha1/imagerepository_types.go
- config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
- controllers/imagerepository_controller.go
- controllers/scan_test.go
This adds support for suspending the scanning of an ImageRepository.
Addresses the first part of #19
> Add support for suspending image scans.

- Makefile
As it does not make error codes surface.
> Remove `find -execdir` from `Makefile`

- api/v1alpha1/imagerepository_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
- controllers/imagerepository_controller.go
- controllers/policy_test.go
- controllers/registry_test.go
- controllers/scan_test.go
- controllers/secret_test.go
- controllers/suite_test.go
- controllers/testdata/secret.json
This lets you create a secret with registry credentials, then refer to it in the `ImageRepository` field `secretRef` so it can be used to scan image repositories that require authentication.
> Use credentials from secret

- .github/workflows/build.yaml
This avoids a hard deprecation in GitHub Actions, of add_path.
> Use kubebuilder action from main

- MAINTAINERS
The GitOps toolkit controllers usually adopt the maintainers of the
"central" Flux v2 git repo, fluxcd/flux2. For convenience of keeping
track, it is easier to refer to the MAINTAINER files there.
NB this expands the maintainers of this repo, but only to those who
were effectively considered maintainers anyway (i.e., it reflects the
established practice.)
See https://github.com/fluxcd/flux2/discussions/515 for the proposal.
> Note shared maintainers from fluxcd/flux2

- Makefile
- api/v1alpha1/doc.go
- docs/api/image-reflector.md
- hack/api-docs/config.json
- hack/api-docs/template/members.tpl
- hack/api-docs/template/pkg.tpl
- hack/api-docs/template/type.tpl
This minimally adapts the API doc generation from kustomize-controller, to work here.
Fixes #42.
> Generate API docs

- controllers/imagerepository_controller.go
- go.mod
- go.sum
- main.go
1. Use the probes package from flucd/pkg for installing health checks
2. Omit suspended objects from metrics (I checked what kustomize-controller does)
> A couple of GOTK-conformance tweaks

- Dockerfile
- config/manager/deployment.yaml
- controllers/database.go
- controllers/imagepolicy_controller.go
- controllers/imagerepository_controller.go
- controllers/suite_test.go
- go.mod
- go.sum
- internal/database/badger.go
- internal/database/badger_test.go
- main.go
This introduces a key/value store for tags, with the keys being the
images and the values being JSON encoded versions of the tags.
The Badger data is stored in a PVC.
Related to #12
> Add BadgerDB as a persistent store for the tag data.

- controllers/suite_test.go
- go.mod
- go.sum
- internal/database/badger.go
- internal/database/badger_test.go
- main.go
We were using Badger v1 while the latest version is v3. This PR upgrades Badger to v3.2011.0 that should fix the `cannot allocate memory` error on RaspberryPI (ref: #82).
> Update Badger to v3.2011.0

- api/go.mod
- api/go.sum
- api/v1alpha1/imagepolicy_types.go
- api/v1alpha1/imagerepository_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/image.toolkit.fluxcd.io_imagepolicies.yaml
- config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
- controllers/policy_test.go
- controllers/scan_test.go
- go.mod
- go.sum
- main.go
Changes:
- update fluxcd/pkg/apis/meta to v0.7.0
- update fluxcd/pkg/runtime to v0.8.0
- hook Kubernetes client and logger flags from runtime
- use LocalObjectReference from fluxcd/pkg/apis/meta in the API
Note that this PR adds two new flags:
```
--kube-api-burst int            The maximum burst queries-per-second of requests sent to the Kubernetes API. (default 50)
--kube-api-qps float32          The maximum queries-per-second of requests sent to the Kubernetes API. (default 20)
```
> Update fluxcd/pkg/runtime to v0.8.0

- go.mod
- go.sum
Includes fixes for ARM 32bit build that we've been using from master
> Update BadgerDB to v3.2011.1

- docs/spec/v1alpha1/imagepolicies.md
In Flux1 we told users to tag their images with `${GIT_BRANCH}-${GIT_SHA:0:7}`, migrating to Flux2 they'll have to change the format to `${GIT_BRANCH}-${GIT_SHA:0:7}-$(date +%s)`.
This PR updates the `ImagePolicy` example to help users craft a policy that filters tags based on branch name and selects the latest build:
```yaml
kind: ImagePolicy
spec:
filterTags:
pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
extract: '$ts'
policy:
alphabetical:
order: asc
``` 
Ref: https://github.com/fluxcd/flux2/discussions/802
> Update ImagePolicy example

- Dockerfile
- config/manager/deployment.yaml
Changes:
- set fsGroup to allow AWS IAM Role bindings 
- fix the group assignment in Alpine
- bump Alpine to 3.13
> Update Alpine to v3.13

- controllers/suite_test.go
- main.go
This was accidentally done while mirroring the work done on the
image-automation-controller. It technically should not hurt, but
should not be either.
Follow up on #132
> Remove v1alpha1 API from Scheme

- controllers/imagepolicy_controller.go
- controllers/policy_test.go
The errors generated by ImagePolicy resources having invalid tag filter
regex patterns were not being reported to the user correctly, no event
was recorded and the ReadyCondition message did not reflect the
encountered error.
Fixes #138
> Ensure invalid regex errors are reported to user

- controllers/imagepolicy_controller.go
- internal/policy/numerical.go
- internal/policy/numerical_test.go
A more verbose message associated with the error should give the user
better understanding of the cause and the nature of the failure.
> Better error reporting for image policy evaluation

- controllers/imagepolicy_controller.go
- controllers/imagerepository_controller.go
- controllers/suite_test.go
- main.go
Default for both, the ImageRepository and the ImagePolicy controllers
is 4 workers.
fix: #148
Signed-off-by: Max Jonas Werner <mail@makk.es>
> Make concurrent reconciliation configurable

- .github/workflows/build.yaml
- Makefile
This removes installing kubebuilder binaries and uses setup-envtest to
install all the necessary envtest helper binaries.
⚠️ target branch of the PR is `reconcilers-dev`.
> Add setup-envtest to makefile & gh build action

- Makefile
Recently added make target `setup-envtest` was added with spaces.
Replace the spaces with tabs for the make target to work.
This wasn't caught in the CI because `setup-envtest` is installed separately
before running `make test`.
:warning: warning target branch of the PR is `reconcilers-dev`.
> Makefile: remove spaces

- controllers/imagepolicy_controller.go
- controllers/policy_test.go
Cross-namespace ImageRepository resources should trigger reconciles for
ImagePolicies that refer to them. Previously, this was only done for
resources in the same namespace.
Fixes #195
> Watched cross-ns image repos trigger reconcile

- controllers/imagepolicy_controller.go
- controllers/policy_test.go
Fixes a regression introduced in v0.13.1
Fixes #198
> Fix watched same-ns image repos trigger reconcile

- go.mod
- go.sum
> Update github.com/opencontainers/image-spec v1.0.2

- api/v1beta1/imagepolicy_types.go
- api/v1beta1/imagerepository_types.go
- config/crd/bases/image.toolkit.fluxcd.io_imagepolicies.yaml
- config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
This sets the status.observedGeneration field to -1 by default. This is to address issue outlined by https://github.com/fluxcd/flux2/issues/2007. 
Signed-off-by: Tom Huang <tom.huang@weave.works>
> Set default observedGeneration to -1

- controllers/imagerepository_controller.go
- controllers/scan_test.go
Adds a descriptive error when an invalid image ref containing a scheme
is given to the ImageRepository.
Fixes #146
> Fix error message on invalid scheme-prefixed ref

- DEVELOPMENT.md
This is to address https://github.com/fluxcd/image-reflector-controller/issues/182. It is recreating changes in https://github.com/fluxcd/image-reflector-controller/pull/191.
> Add various instructions on development documentation

- .github/workflows/build.yaml
- .gitignore
- Makefile
Refactor logic to install helper tools into one function in the
Makefile. Add support for envtest to help install tools like kubectl,
etcd which helps users run tests more conveniently.
Signed-off-by: Sanskar Jaiswal <sanskar.jaiswal@weave.works>
Ref: https://github.com/fluxcd/flux2/issues/2273
> Fix makefile envtest and controller-gen usage

- .github/workflows/scan.yml
- controllers/imagerepository_controller.go
- docs/spec/v1beta1/imagerepositories.md
- go.mod
- go.sum
- internal/azure/exchanger.go
- main.go
Closes #180 
Closes #179 
This pull request adds two flags (`gcp-autologin-for-gcr` and `azure-autologin-for-acr`) for autologin on GCP and Azure to their container registries.
This has been tested on GKE clusters with workload identities enabled and default service account.
This has been tested on an AKS w Managed Identities.
Further refactoring could be done to move implementation details of various cloud providers into a dedicated package.
Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>
> Get credentials from GCP/Azure when needed

- controllers/imagerepository_controller.go
A little follow-up on the #194 to ensure the response body is closed regardless of status code
Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>
> GCR fix: Discard and close body regardless of status code

- controllers/imagerepository_controller.go
- controllers/scan_test.go
The validation check for the presence of a scheme did not take into
account situations when the registry hostname would be accompanied by a
port number. In this situation, the hostname would be erroneously parsed
as a scheme and validation would fail.
Fixes #220
> Fix scheme validation check when using host:port

- docs/spec/v1alpha2/imagerepositories.md
- docs/spec/v1beta1/imagerepositories.md
Leans on:
* #194,
(but I think they can merge in either order)
Slimmed-down replacement version of #193 that takes into account most other things that were to be fixed here, are fixed by fluxcd/website#702
There was a usability issue reported in the docs that I meant to address here, and it's not obvious from the structure of the change, but as the `ImageRepositories` controller API docs are not obviously associated with the `image-reflector-controller` where they are most accessible (on the website, [here](https://fluxcd.io/docs/components/image/imagerepositories/#ecr-and-eks) in the API docs)
There is no breadcrumb which says `image-reflector-controller` visible anywhere on the page, so it's necessary to spell out which controller needs to get the flag.
In fluxcd/website#702 a detailed …
> Clarify ECR Auto-login note, fix CanonicalImageName typos

- MAINTAINERS
This moves me into the "Retired maintainers" category. The format is intended to work with the script https://github.com/fluxcd/community/blob/main/project/get_project_data.
> Move squaremo to retired maintainers

- controllers/policy_test.go
- controllers/registry_test.go
- controllers/scan_test.go
- controllers/tls_test.go
- internal/test/registry.go
- tests/fuzz/fuzz_controllers.go
- tests/fuzz/oss_fuzz_build.sh
[oss-fuzz](https://github.com/google/oss-fuzz) in coverage mode was broken due to duplicate symbols. Refactoring the registry test code and referencing it directly fixes it.
> Refactor registry test code and fix fuzz integration

- controllers/imagerepository_controller.go
The scope is missing a `/.default` at the end and thereby prevented me from acquiring a valid access token.
Azure requires a full scope and not only the URL to be able to acquire a token. As the flow uses application permissions and not delegate permissions, the scope needs to end in "/.default" as described in https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#request-the-permissions-in-the-app-registration-portal
> fix: Invalid Azure Scope

- controllers/imagerepository_controller.go
- controllers/scan_test.go
- docs/api/image-reflector.md
- hack/api-docs/config.json
Reject image repositories when `.spec.image` contains a tag and set the ready status to:
```
.spec.image value should not contain a tag; remove ':tag'
```
Fix: #267
> Validate that the image name does not contain tags

- controllers/imagerepository_controller.go
Deferred function calls are executed in Last In First Out order after the surrounding function returns, so we should make sure io.Copy() is executed before close().
Signed-off-by: Soule BA <bah.soule@gmail.com>
> Fix response body read and close defer order

- api/v1beta1/imagepolicy_types.go
- api/v1beta1/imagerepository_types.go
- controllers/imagepolicy_controller.go
- controllers/imagerepository_controller.go
Fixes https://github.com/fluxcd/image-reflector-controller/issues/225
This PR adds a finalizer to the ImagePolicy and ImageRepository resources. This is to properly record the Deleted reconciliation status when the object is deleted from the cluster. Without this change, the resource would be deleted before the image reflector controller has a chance to properly report the resource's status in the metrics. As a result, end-users may see falsely reported metrics.
Signed-off-by: Kaden Nelson <kaden_l_nelson@apple.com>
> Add a finalizer to the ImagePolicy and ImageRepository resources

- controllers/imagerepository_controller.go
- internal/registry/aws/auth.go
- internal/registry/aws/auth_test.go
- internal/registry/azure/auth.go
- internal/registry/azure/auth_test.go
- internal/registry/azure/exchanger.go
- internal/registry/azure/exchanger_test.go
- internal/registry/azure/fake.go
- internal/registry/constants.go
- internal/registry/errors.go
- internal/registry/gcp/auth.go
- internal/registry/gcp/auth_test.go
- internal/registry/login/login.go
- internal/registry/login/login_test.go
- internal/test/registry.go
- main.go
`internal/registry` package consolidates all the registry provider logins.
The `internal/registry/login` package contains a login `Manager` which
manages logins for all the providers. For testability, it provides methods to
modify the provider client configurations.
`internal/registry/{aws/azure/gcp}` packages contain clients for logging
into the respective registry. The client APIs are mostly similar across all the
providers, except for the small details related to overriding certain
configurations for testing purposes. Each of the providers have test
coverage to solidify the expected behavior in different scenarios.
This depends on #275 for testing to ensure that the native registry login
tests work before and after these changes.
NOTE: I'd like to gain some confidence in this package, …
> Introduce registry package

- tests/integration/Makefile
- tests/integration/README.md
- tests/integration/aws_test.go
- tests/integration/azure_test.go
- tests/integration/gcp_test.go
- tests/integration/suite_test.go
- tests/integration/terraform/aws/ecr.tf
- tests/integration/terraform/aws/outputs.tf
- tests/integration/utils.go
Update the cloud provider e2e test suite to take the image-reflector-controller
build to be tested using the variable `TEST_IMG`. This test image must be
built locally before running the e2e tests. In the e2e tests, this local image
is re-tagged and pushed into a remote registry and is used in flux deployment.
For Google Artifact Registry and Azure Container Registry, the
previously created test registries are reused to push the
image-reflector image. But for ECR, a new repository is created due to
lack of support for dynamic repositories.
> cloud-provider-e2e: Use test image-reflector build

- controllers/imagerepository_controller.go
- controllers/scan_test.go
When a given image reference is identified as a known provider but is
unconfigured, continue the reconciliation and scan to be able to scan
public repositories. Abort the reconciliation for any other error during
login.
Also add a test for scanning public repos without rate limits.
Fixes https://github.com/fluxcd/image-reflector-controller/issues/289
> imagerepo: Continue scan for unconfigured provider

- .github/workflows/scan.yml
- go.mod
- go.sum
pkg/oci v0.2.0 uses azure SDK v1.
Verified that the IRC autologin continues to work on azure by running the integration test.
> Update pkg/oci to v0.2.0

- controllers/imagepolicy_controller.go
- controllers/imagerepository_controller.go
- main.go
Add two new flags to enable users to configure exponential back-off for Flux objects. The default values are now set to 750ms for minimum retry time, and 15min for max.
Fixes: https://github.com/fluxcd/image-reflector-controller/issues/246.
> Add flags to configure exponential back-off retry

- controllers/imagepolicy_controller.go
At controller restart, it is quite common to experience `Cannot determine latest tag for policy: version list argument cannot be empty` errors. This happens because the existing repository may be Ready, but all its underlying data has been lost as it resides in the controller. 
Instead of erroring, this PR tries to self-heal by postponing the Policy reconciliation based on its repository set interval.
As a result, the controller will log:
`
{"level":"info","ts":"2022-08-08T17:37:52.544Z","logger":"controller.imagepolicy","msg":"no tags found in 'my-image-policy', retrying in 1m0s","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImagePolicy","name":"source-controller","namespace":"flux-system"}
`
And generate a Kubernetes Event with similar information.
Fixes: …
> Skip error policy reconciliation if no tags are found

- api/v1beta1/imagerepository_types.go
- config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
To solve discrepancies between parsing versus validation.
xref: https://github.com/kubernetes/apimachinery/issues/131
> api: add custom validation for v1.Duration types

- controllers/controllers_fuzzer_test.go
- tests/fuzz/README.md
- tests/fuzz/oss_fuzz_build.sh
- tests/fuzz/oss_fuzz_prebuild.sh
Establish conventions which aligns with what is supported upstream today, whilst expanding on documentation to ensure folks have pointers on how to debug/check for issues going forwards.
> build: Improve fuzz tests' reliability

- controllers/imagerepository_controller.go
- main.go
Use the value of autologin flags if `spec.provider` is not set or set to `generic`.
Fixes #352
> Fallback to autlogin flags if no provider is specified

- go.mod
- go.sum
Update `github.com/fluxcd/pkg/oci` to v0.29.0 that includes https://github.com/fluxcd/pkg/pull/600
> Update `fluxcd/pkg/oci` to fix ECR cross-region auth

- Makefile
- docs/api/v1beta2/image-reflector.md
- docs/spec/v1beta2/imagepolicies.md
- docs/spec/v1beta2/imagerepositories.md
- hack/api-docs/template/pkg.tpl
In some controller we already support multiple API versions at the same time. In order to streamline the docs structure, the necessary changes to do the same in this repo are applied here as well.
refs fluxcd/website#1577
> Align docs structure with other controllers

- CHANGELOG.md
- config/manager/kustomization.yaml
- go.mod
Part of: https://github.com/fluxcd/flux2/issues/4125
> Release v0.30.0

- api/v1beta2/imagerepository_types.go
- config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
- docs/api/v1beta2/image-reflector.md
- docs/spec/v1beta2/imagerepositories.md
- internal/controller/imagerepository_controller.go
- internal/controller/imagerepository_controller_test.go
Add a new boolean field `.spec.insecure` to the `ImageRepository` API. This enables connecting to insecure registries hosted at an HTTP endpoint.
Fixes #325 
Related to https://github.com/fluxcd/flux2/tree/main/rfcs/0004-insecure-http
> imagerepo: add `.spec.insecure` to `ImageRepository`

- docs/spec/v1beta2/imagerepositories.md
Added a note for EKS gotcha that I struggled with.  Hopefully makes it easier for the next person.
> Add note to restart image-reflector-controller after AWS IAM role change

- docs/spec/v1beta2/imagerepositories.md
Remove references to the deprecated Azure AAD pod identity
> docs: Remove references to aad pod identity

- internal/controller/imagepolicy_controller.go
- internal/controller/imagerepository_controller.go
The `Mark…` functions in the `conditions` package accept a format string and (optional) arguments, just like `fmt.Printf` and friends.
In many places, the code passed an error message as the format string, causing it to be interpreted as a format string by the `fmt` package. This leads to issues when the message contains percent signs, e.g. URL-encoded values.
This PR adds a format string and shortens `err.Error()` to `err`, which yields the same output.
This change is identical in principle to fluxcd/source-controller#1529.
> Fix incorrect use of format strings with the `conditions` package.

- internal/controller/imagepolicy_controller.go
- internal/controller/imagerepository_controller.go
Suspend and readiness metrics recording removed from ImageRepository and ImagePolicy reconcilers.
Refer https://github.com/fluxcd/flux2/issues/5083.
> Remove deprecated object metrics

- Makefile
- config/rbac/role.yaml
- docs/spec/v1beta2/imagerepositories.md
- go.mod
- go.sum
- internal/controller/imagepolicy_controller.go
- internal/controller/imagerepository_controller.go
- main.go
Depends on: https://github.com/fluxcd/pkg/pull/919
Part of: https://github.com/fluxcd/flux2/issues/5022
This PR also introduces a token cache for caching the cloud provider access tokens. This token cache will report the following metrics:
* Counter `gotk_token_cache_events_total`
* Help: `Total number of cache retrieval events for a Gitops Toolkit resource reconciliation.`
* Labels: `event_type`, `kind`, `name`, `namespace`, `operation`. The values of `event_type` can be `cache_miss` or `cache_hit`. The value of `operation` is always `reconcile`.
* Counter `gotk_token_cache_requests_total`
* Help: `Total number of cache requests partioned by success or failure.`
* Labels: `status`. The values of `status` can be `success` or `failure`.
* Counter `gotk_token_cache_evictions_total`
* Help: …
> [RFC-0010] Introduce object-level workload identity for ImageRepository

- go.mod
- go.sum
- internal/controller/imagerepository_controller.go
- internal/registry/options.go
- internal/registry/options_test.go
- main.go
Remove support for deprecated auto-login controller flags as part of preparing image automation APIs for GA.
This addresses task 3 "Remove deprecated code paths (e.g. auto-login flags in IRC)" from https://github.com/fluxcd/flux2/issues/5411.
Removes the following flags that have been deprecated since v0.25.0:
- `--aws-autologin-for-ecr`
- `--gcp-autologin-for-gcr` 
- `--azure-autologin-for-acr`
- Remove flag definitions and variables from main.go
- Remove `DeprecatedLoginOpts` field from `ImageRepositoryReconciler`
- Remove deprecated login options handling from registry options
- Clean up unused imports (`errors`, `aws`, `azure`, `gcp` packages)
- Clarify switch statement logic for provider auto-login
This is a **planned breaking change** for flags that have been deprecated since …
> Remove deprecated auto-login flags

- api/v1beta2/imagerepository_types.go
- config/crd/bases/image.toolkit.fluxcd.io_imagerepositories.yaml
- docs/api/v1beta2/image-reflector.md
- internal/controller/database.go
- internal/controller/imagepolicy_controller.go
- internal/controller/imagepolicy_controller_test.go
- internal/controller/imagerepository_controller.go
- internal/controller/imagerepository_controller_test.go
- internal/database/badger.go
- internal/database/badger_gc_test.go
- internal/database/badger_test.go
Closes #778 
There's already a field called `.spec.lastScanResult` with other information about the scan that is pretty close to `revision` (e.g. `tagCount`, `latestTags`), so I figured it would make more sense to put the revision inside it as well.
> Store checksum of ImageRepository tags and trigger ImagePolicy watch only when it changes

- internal/controller/imagepolicy_controller.go
- internal/controller/imagepolicy_controller_test.go
- internal/controller/imagerepository_controller.go
- internal/controller/imagerepository_controller_test.go
While working on https://github.com/fluxcd/flux2/pull/5492 we noticed that the ImagePolicy controller was lacking the predicate for watching reconcile requests from the annotation. This bug escaped due to a weakness on the controller test for this scenario where the object was being created with the annotation, so the first reconciliation was copying the annotation to the status field. After changing this test to create the object without the annotation and to add it later, the test started to fail, making the bug surface.
We are also improving the same test for the ImageRepository controller, and modifying its predicate setup to match the style of the majority of the other controllers.
> Fix controllers not watching reconcile requests from annotations
